{% set name = "xsocs" %}
{% set version = "2024.9.0" %}

package:
  name: xsocs-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xsocs-{{ version }}.tar.gz
  sha256: eed72f3e5de681a08d55d36575b520739ed49019f3ed39f2b5cd2fe2dcf9194e

build:
  number: 0

outputs:
  - name: xsocs-base
    build:
      noarch: python
      script: python -m pip install --no-deps --no-build-isolation -vv .
      entry_points:
        - xsocs = xsocs.__main__:main

    requirements:
      host:
        - python >=3.7
        - wheel
        - setuptools
        - pip
      run:
        - python >=3.7
        - numpy
        - h5py
        - fabio
        - silx-base >=1.0.0
        - xrayutilities
        - scipy
        - setuptools

    test:
      imports:
        - xsocs
      commands:
        - pip check
        - xsocs --help
        - python -c "import sys, xsocs.test; sys.exit(xsocs.test.run_tests(verbosity=3))"
      requires:
        - pip

  - name: xsocs
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('xsocs-base', exact=True) }}
        - silx >=1.0.0
        - pyopengl
        - matplotlib-base
        - pyqt
    test:
      imports:
        - xsocs
      commands:
        - xsocs gui --help
        - pip check
      requires:
        - pip

about:
  home: https://gitlab.esrf.fr/kmap/xsocs
  summary: Xray Strain Orientation Calculation Software
  license: MIT
  license_file: LICENSE
  doc_url: https://kmap.gitlab-pages.esrf.fr/xsocs/
  dev_url: https://gitlab.esrf.fr/kmap/xsocs

extra:
  recipe-maintainers:
    - t20100
  feedstock-name: xsocs
